# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2022-04-25 09:20:05
"""
import arcpy
from NewToolbox.Step01_01_LandUseBuildingPermits import Step01_01_LandUseBuildingPermits
from NewToolbox.Step01_02_AreaUnion import Step01_02_AreaUnion
from NewToolbox.Step02_Subdivisions import Step02_Subdivisions
from NewToolbox.Step03_PotentialGrowthAreas import Step03_PotentialGrowthAreas
from sys import argv

def FullProcess_Stitched(LawrenceZoning="\\\\GISFile\\gisdata\\Department\\MSO\\Projects\\Internal\\CHM_Gontwz_landuseSuitabilityRerun\\Gonterwitz_Suitability_Rerun2022\\Gonterwitz_Suitability_Rerun2022.gdb\\LawrenceZoning", Results_2022="\\\\GISFile\\gisdata\\Department\\MSO\\Projects\\Internal\\CHM_Gontwz_landuseSuitabilityRerun\\Gonterwitz_Suitability_Rerun2022\\RESULTS_GontzGrowthProcess.gdb\\Results_2022", ParcelPoints="\\\\GISFile\\gisdata\\Department\\MSO\\Projects\\Internal\\CHM_Gontwz_landuseSuitabilityRerun\\Gonterwitz_Suitability_Rerun2022\\RESULTS_GontzGrowthProcess.gdb\\Results_2022\\ParcelPoints"):  # FullProcess_Stitched

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    # Model Environment settings
    with arcpy.EnvManager(outputCoordinateSystem="PROJCS["NAD_1983_StatePlane_Kansas_North_FIPS_1501_Feet",GEOGCS["GCS_North_American_1983",DATUM["D_North_American_1983",SPHEROID["GRS_1980",6378137.0,298.257222101]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Lambert_Conformal_Conic"],PARAMETER["False_Easting",1312333.333333333],PARAMETER["False_Northing",0.0],PARAMETER["Central_Meridian",-98.0],PARAMETER["Standard_Parallel_1",38.71666666666667],PARAMETER["Standard_Parallel_2",39.78333333333333],PARAMETER["Latitude_Of_Origin",38.33333333333334],UNIT["Foot_US",0.3048006096012192]]"):
        BuildingPermits_Building_Permit = "BuildingPermits - Building Permit"
        LandUse2021 = "\\\\GISFile\\gisdata\\Department\\MSO\\Projects\\Internal\\CHM_Gontwz_landuseSuitabilityRerun\\Gonterwitz_Suitability_Rerun2022\\Gonterwitz_Suitability_Rerun2022.gdb\\LandUse2021"
        BuildingFootprints = "\\\\GISFile\\gisdata\\Department\\MSO\\Projects\\Internal\\CHM_Gontwz_landuseSuitabilityRerun\\Gonterwitz_Suitability_Rerun2022\\Gonterwitz_Suitability_Rerun2022.gdb\\BuildingFootprints"
        Results_2022_3_ = "\\\\GISFile\\gisdata\\Department\\MSO\\Projects\\Internal\\CHM_Gontwz_landuseSuitabilityRerun\\Gonterwitz_Suitability_Rerun2022\\RESULTS_GontzGrowthProcess.gdb\\Results_2022"
        Lot_2_ = "Lot"
        Zoning2022 = "\\\\GISFile\\gisdata\\Department\\MSO\\Projects\\Internal\\CHM_Gontwz_landuseSuitabilityRerun\\Gonterwitz_Suitability_Rerun2022\\RESULTS_GontzGrowthProcess.gdb\\Results_2022\\Zoning2022"

        # Process: Step01_01_LandUseBuildingPermits (2) (Step01_01_LandUseBuildingPermits) (NewToolbox)
        LandUseBuildingPermits_type02_3_ = "\\\\GISFile\\gisdata\\Department\\MSO\\Projects\\Internal\\CHM_Gontwz_landuseSuitabilityRerun\\Gonterwitz_Suitability_Rerun2022\\RESULTS_GontzGrowthProcess.gdb\\Results_2022\\LandUseBuildingPermits_type02"
        Step01_01_LandUseBuildingPermits(Building_Permit_Points=BuildingPermits_Building_Permit, Land_Use=LandUse2021, Building_Footprints=BuildingFootprints, LandUseBuildingPermits_type02=LandUseBuildingPermits_type02_3_, Workspace_GDB=Results_2022_3_)

        # Process: Step03_PotentialGrowthAreas (2) (Step03_PotentialGrowthAreas) (NewToolbox)
        VacantUnpermitted_v2_2_, PotentialGrowthArea_v2_Layer1, PotentialGrowthArea_v1_Layer_2_ = Step03_PotentialGrowthAreas(Land_Use_and_Buildping_Permits_combined_as_polygons=LandUseBuildingPermits_type02_3_, Current_Lawrence_Zoning=LawrenceZoning, Workspace_GDB=Results_2022)

        # Process: Step01_02_AreaUnion (2) (Step01_02_AreaUnion) (NewToolbox)
        AreaUnion = "\\\\GISFile\\gisdata\\Department\\MSO\\Projects\\Internal\\CHM_Gontwz_landuseSuitabilityRerun\\Gonterwitz_Suitability_Rerun2022\\RESULTS_GontzGrowthProcess.gdb\\Results_2022\\AreaUnion"
        Step01_02_AreaUnion(Plats_by_Lot=Lot_2_, AreaUnion=AreaUnion, Lawrence_ZOning=Zoning2022, Workspace_GDB=Results_2022, Land_Use_and_Building_Permits_by_polygon=LandUseBuildingPermits_type02_3_)

        # Process: Step02_Subdivisions (Step02_Subdivisions) (NewToolbox)
        Subdivisions_v4 = "\\\\GISFile\\gisdata\\Department\\MSO\\Projects\\Internal\\CHM_Gontwz_landuseSuitabilityRerun\\Gonterwitz_Suitability_Rerun2022\\RESULTS_GontzGrowthProcess.gdb\\Results_2022\\Subdivisions_v4"
        Step02_Subdivisions(AreaUnion=AreaUnion, Land_Use_and_Building_Permits_by_polygon=LandUseBuildingPermits_type02_3_, FINAL_Subdivisions=Subdivisions_v4, Parcels_as_Points=ParcelPoints, Results_2022=Results_2022)

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(extent="2045727.39081031 209617.596123308 2138008.89555138 274945.453000143", scratchWorkspace=r"\\GISFile\gisdata\Department\MSO\Projects\Internal\CHM_Gontwz_landuseSuitabilityRerun\Gonterwitz_Suitability_Rerun2022\RESULTS_GontzGrowthProcess.gdb\Results_2022", workspace=r"\\GISFile\gisdata\Department\MSO\Projects\Internal\CHM_Gontwz_landuseSuitabilityRerun\Gonterwitz_Suitability_Rerun2022\RESULTS_GontzGrowthProcess.gdb\Results_2022"):
        FullProcess_Stitched(*argv[1:])
